---
title: "Rapport arbeidskrav 6"
author: Karoline Simpson-Larsen
format: pdf
Bibliography: referanser/referanser.bib

---

# Introduksjon

Adaptasjoner til styrketrening varierer fra person til person, og henger sammen med en rekke faktorer, som treningsvolum, intensitet, valg av øvelser, hvile mellom sett, hastighet på utførelsen av øvelsen og hyppigheten på treninga (@ratamess2009). I tillegg spiller genetiske disposisjoner og miljøfaktorer en rolle for variasjoner i tilpasninger (@timmons2011). Styrketrening har en positv effekt på prestasjon i mange idretter som stiller krav til styrke, men også utholdenhetsidrett (@beattie2014; @rønnestad2014). I tillegg har styrketrening en positv effekt sett i et folkehelseperspektiv (@westcott). 

For utrente personer som begynner med styrketrening varierer økningen i muskelstyrke med 1 %, målt som 1RM, med en variasjon på 0,1-0,3% (@mcdonagh1984), samt at tvversnittet til de musklene som trenes økes med 0,1-0,5% per økt (@wernbom2007). Variasjonene i adaptasjonene på styrke- og muskelvekst er sannsynligvis avhengig av hvilken muskelgruppe som trenes, antall serier og repetisjoner, pauselengde, fibertypesammensetning og genetikk (@raastad2010; @tonnessen2018)

Målet med denne studien var å sammenlikne effekten av singel- og multiserie (3 sett) treningsprotokoller på muskelstyrke og muskelmasse. 

# Metode

## Deltaktere

Det ble rekruttert 41 mannlige og kvinnelige deltaktere til å delta i studien, med ett kriteritum om å være ikke-røykere og mellom 18 og 40 år. Ekslusjonskriterer var intoleranse av lokal bedøvelse, redusert muskelstyrke på grunn av tidligere eller nåværende skader, gjennomført mer enn én styrkeøkt i uka det siste året før intervensjonen og inntak av medisiner som kan påvirke adaptasjoner til styrketrening. I dataanalysene ble syv deltakere ekskludert fordi de ikke fullført 85% av de planlagte treningsøktene av ulike grunner. Alle deltakerne hadde tidligere erfaring med idrettsaktiviteter som for eksempel lagidretter, langrenn og turn. 

## Studiedesign

Intervensjonsperioden bestod av 12 uker med styrketrening på helkropp, gjennomført mellom september og november. Bein-øvelsene ble gjennomført seperat for hvert enkelt bein, for å muliggjøre differensiering av treningsvolum på samme deltaker. Hver deltaker ble tilfeldig tildelt enten single-set eller 3-set program for hvert enkelt bein. Hver deltaker gjennomførte dermed to ulike protokoller. Maksimal muskelstyrke ble målt før-, i uke 3, 5 og 9-, og etter intervensjonen. Kroppssammensetningen ble målt før og etter intervensjonen. I tillegg ble det tatt muskelbiopsi fra hvert bein fra vastus lateralis i uke 0 i hvilt tilstand, før og etter 1 time etter femte treningsøkt, og etter fullført treningsintervensjon i hvilt tilstand. 

